app/__init__.py
from flask import Flask
import crochet

crochet.setup()

def create_app(config):
    app = Flask(__name__)

    app.config.from_mapping(
        SECRET_KEY = 'dev',
    )

    from .views import bp
    app.register_blueprint(bp)

    return app

app/bbc_crawler/bbc_crawler/spiders/__init__.py
# This package will contain the spiders of your Scrapy project
#
# Please refer to the documentation for information on how to create and manage
# your spiders.

app/views.py
from flask import abort, Blueprint, flash, g, redirect, render_template, request, url_for
from .db import get_client
from . import crochet
import pymongo
from bson.objectid import ObjectId
from scrapy.crawler import CrawlerRunner
from .bbc_crawler.bbc_crawler.spiders.articlescrawler import ArticleSpider
import re

bp = Blueprint('views', __name__)


@bp.route('/', methods = ('GET', 'POST'))
def index():
    client = get_client()
    collection = client['news']
    if request.method == 'POST':
        search = request.form.get('search')
        if search:
            research = re.compile('.*' + search + '.*', re.IGNORECASE)
            articles = collection.articles_final1.find({"$or" : [{"title_s" : research}, {"author" : research}, {"content_s" : research}]}, {"_id" : 1,"title" : 1, "author" : 1, "date" : 1}).sort("date_s", pymongo.DESCENDING)
            return render_template('index.html', datas = articles, search = search)
        else:
            flash('검색하신 입력값이 없습니다.')

    articles = collection.articles_final1.find({}, {"_id" : 1, "title" : 1, "author" : 1, "date" : 1}).sort([("date_s", pymongo.DESCENDING), ("_id", pymongo.DESCENDING)])
    return render_template('index.html', datas = articles, search = None)


@bp.route('/crawling')
def crawling():
    scrape_with_crochet()
    return render_template('crawling.html')


@crochet.run_in_reactor
def scrape_with_crochet():
    runner = CrawlerRunner().crawl(ArticleSpider)


@bp.route('/articles/<_id>')
def articles(_id):
    collection = get_client()['news']
    article = collection.articles_final1.find_one({'_id' : ObjectId(_id)}, {"title" : 1, "author" : 1, "date" : 1, "content_r" : 1, "url" : 1})
    return render_template('articles.html', article = article)

app/templates/articles.html
{% extends "base.html" %}

{% block header %}
<div class="container">
 <div class="row">
  <div class="col-sm-1">
   <a href="{{ url_for('views.index') }}">
    <img class="back-arrow" src="{{ url_for('static', filename='icon/return_Freepik.png') }}">
   </a>
  </div>
  <div class="col-sm-10">
   <h1>{{ article.get('title') }}</h1>
  </div>
 </div>
</div>
{% endblock %}
{% block body %}
<section class="mt-3">
 <div class="mt-4">
  <div>
   <h4 class="author">{{ article.get('author') }}</h4>
   <h5 class="date">{{ article.get('date') }}</h5>
  </div>
  <div class="container">
   {{article.get('content_r') | safe}}
  </div>
 </div>
</section>
{% endblock %}
{% block footer %}
<footer class="main-footer">
 <div class="container">
  <h6 class="original">원문 : <a href="{{ article.get('url') }}">{{ article.get('url') }}</a></h6>
  <div>Icons made by <a href="https://www.flaticon.com/authors/freepik" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div>
 </div>
</footer>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html>
 <head>
  <meta charset="utf-8">
  <title>BBC Crawler</title>
  <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

  <!-- Popper JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
 </head>
 <body>
  <header class="main-h">
   {% block header %}{% endblock %}
  </header>
  <main class="container">
   {% block body %}{% endblock %}
  </main>
  {% block footer %}
  {% endblock %}
 </body>
</html>

app/templates/crawling.html
{% extends "base.html" %}
{% block header %}
 <div>
  <div>
   <form class="inner-line search-area" action="{{ url_for('views.index') }}" method="post">
    <div class="inner-line search-box">
     <input type="text" id="" name="search" value="{{search}}" />
    </div>
    <div class="inner-line">
     <button type="submit" id="" class="">Search</button>
    </div>
   </form>
   <div class="inner-line button-area">
    <div class="top-margin">
     <a href="{{url_for('views.crawling')}}" class="crawl-btn">Crawling</a>
    </div>
    <div class="top-margin">
     <a href="{{url_for('views.index')}}" class="view-all-btn">전체 글 보기</a>
    </div>
   </div>
  </div>
 </div>
{% endblock %}
{% block body %}
 <section class="container">
  <div class="container">
   <h1>Crawling이 완료 되었습니다.</h1>
   <h3><a href="{{ url_for('views.index') }}">결과 보기.</a></h3>
  </div>
 </section>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% block header %}
 <div>
  <div>
   <form class="inner-line search-area" method="post">
    <div class="inner-line search-box">
     {% if search %}
      <input type="text" id="" name="search" value="{{search}}" />
     {% else %}
      <input type="text" id="" name="search" value="" />
     {% endif %}
    </div>
    <div class="inner-line">
     <button type="submit" id="" class="">Search</button>
    </div>
   </form>
   <div class="inner-line button-area">
    <div class="top-margin">
     <a href="{{url_for('views.crawling')}}" class="crawl-btn">Crawling</a>
    </div>
    <div class="top-margin">
     <a href="{{ url_for('views.index') }}" class="view-all-btn">전체 글 보기</a>
    </div>
   </div>
  </div>
 </div>
{% endblock %}
{% block body %}
 {% if get_flashed_messages() %}
  <ul>
  {% for message in get_flashed_messages() %}
   <li class="alert alert-warning">{{message}}</li>
  {% endfor %}
  </ul>
 {% endif %}
 <section class="container">
  <div class="container">
  {% if datas %}
   {# 존재하는 경우 #}
   <table class="table">
    <tr>
     <th>제목</th>
     <th>기자</th>
     <th>작성날짜</th>
     <th></th>
    </tr>
    {% for data in datas %}
     <tr>
      <td>
       <a href="{{ url_for('views.articles', _id = data.get('_id')) }}">{{data.get('title')}}</a>
      </td>
      <td>{{data.get('author')}}</td>
      <td>{{data.get('date')}}</td>
      <td>
       <a href="#">X</a>
      </td>
     </tr>
    {% endfor %}
   </table>
  {% else %}
   <h1>존재하는 데이터가 없습니다.</h1>
  {% endif %}
  </div>
 </section>
{% endblock %}